// <auto-generated />
using System;
using AlgoTrading.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlgoTrading.Infrastructure.Migrations
{
    [DbContext(typeof(AlgoTradingDbContext))]
    [Migration("20251109152759_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlgoTrading.Core.Entities.Audit.AuditLog", b =>
                {
                    b.Property<DateTime>("LogTimestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("log_timestamp");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("user_ip");

                    b.HasKey("LogTimestamp", "Id");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("idx_audit_entity");

                    b.HasIndex("UserId", "LogTimestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_audit_user");

                    b.ToTable("audit_logs", "audit");
                });

            modelBuilder.Entity("AlgoTrading.Core.Entities.MarketData.MarketData", b =>
                {
                    b.Property<string>("StockCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("stock_code");

                    b.Property<DateTime>("DataTimestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("data_timestamp");

                    b.Property<decimal?>("ChangePercent")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("change_percent");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MarketStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("market_status");

                    b.Property<int?>("TradeCount")
                        .HasColumnType("integer")
                        .HasColumnName("trade_count");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasKey("StockCode", "DataTimestamp");

                    b.HasIndex("StockCode", "DataTimestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_market_data_stock");

                    b.ToTable("market_data", "market");
                });

            modelBuilder.Entity("AlgoTrading.Core.Entities.MarketData.OrderBook", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("AskVolume1")
                        .HasColumnType("bigint")
                        .HasColumnName("ask_volume_1");

                    b.Property<long?>("AskVolume10")
                        .HasColumnType("bigint")
                        .HasColumnName("ask_volume_10");

                    b.Property<long?>("AskVolume2")
                        .HasColumnType("bigint")
                        .HasColumnName("ask_volume_2");

                    b.Property<long?>("AskVolume3")
                        .HasColumnType("bigint")
                        .HasColumnName("ask_volume_3");

                    b.Property<long?>("AskVolume4")
                        .HasColumnType("bigint")
                        .HasColumnName("ask_volume_4");

                    b.Property<long?>("AskVolume5")
                        .HasColumnType("bigint")
                        .HasColumnName("ask_volume_5");

                    b.Property<long?>("AskVolume6")
                        .HasColumnType("bigint")
                        .HasColumnName("ask_volume_6");

                    b.Property<long?>("AskVolume7")
                        .HasColumnType("bigint")
                        .HasColumnName("ask_volume_7");

                    b.Property<long?>("AskVolume8")
                        .HasColumnType("bigint")
                        .HasColumnName("ask_volume_8");

                    b.Property<long?>("AskVolume9")
                        .HasColumnType("bigint")
                        .HasColumnName("ask_volume_9");

                    b.Property<long?>("BidVolume1")
                        .HasColumnType("bigint")
                        .HasColumnName("bid_volume_1");

                    b.Property<long?>("BidVolume10")
                        .HasColumnType("bigint")
                        .HasColumnName("bid_volume_10");

                    b.Property<long?>("BidVolume2")
                        .HasColumnType("bigint")
                        .HasColumnName("bid_volume_2");

                    b.Property<long?>("BidVolume3")
                        .HasColumnType("bigint")
                        .HasColumnName("bid_volume_3");

                    b.Property<long?>("BidVolume4")
                        .HasColumnType("bigint")
                        .HasColumnName("bid_volume_4");

                    b.Property<long?>("BidVolume5")
                        .HasColumnType("bigint")
                        .HasColumnName("bid_volume_5");

                    b.Property<long?>("BidVolume6")
                        .HasColumnType("bigint")
                        .HasColumnName("bid_volume_6");

                    b.Property<long?>("BidVolume7")
                        .HasColumnType("bigint")
                        .HasColumnName("bid_volume_7");

                    b.Property<long?>("BidVolume8")
                        .HasColumnType("bigint")
                        .HasColumnName("bid_volume_8");

                    b.Property<long?>("BidVolume9")
                        .HasColumnType("bigint")
                        .HasColumnName("bid_volume_9");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("captured_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("stock_code");

                    b.Property<long?>("TotalAskVolume")
                        .HasColumnType("bigint")
                        .HasColumnName("total_ask_volume");

                    b.Property<long?>("TotalBidVolume")
                        .HasColumnType("bigint")
                        .HasColumnName("total_bid_volume");

                    b.HasKey("Id");

                    b.HasIndex("StockCode", "CapturedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_orderbook_stock_time");

                    b.ToTable("order_book", "market");
                });

            modelBuilder.Entity("AlgoTrading.Core.Entities.MarketData.StockInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("stock_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Industry")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("industry");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean")
                        .HasColumnName("is_suspended");

                    b.Property<bool>("IsTradable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_tradable");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ListedShares")
                        .HasColumnType("bigint")
                        .HasColumnName("listed_shares");

                    b.Property<DateTime?>("ListingDate")
                        .HasColumnType("date")
                        .HasColumnName("listing_date");

                    b.Property<string>("MarketType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("market_type");

                    b.Property<string>("Sector")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sector");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stock_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MarketType")
                        .HasDatabaseName("idx_stock_info_market");

                    b.HasIndex("Sector")
                        .HasDatabaseName("idx_stock_info_sector");

                    b.ToTable("stock_info", "market");
                });

            modelBuilder.Entity("AlgoTrading.Core.Entities.MarketData.TickData", b =>
                {
                    b.Property<string>("StockCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("stock_code");

                    b.Property<DateTime>("TickTimestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("tick_timestamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExecutionSide")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("execution_side");

                    b.Property<long>("ExecutionVolume")
                        .HasColumnType("bigint")
                        .HasColumnName("execution_volume");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StockCode", "TickTimestamp");

                    b.HasIndex("StockCode", "TickTimestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_tick_stock_time");

                    b.ToTable("tick_data", "market");
                });

            modelBuilder.Entity("AlgoTrading.Core.Entities.Monitoring.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("acknowledged_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("alert_status");

                    b.Property<Guid?>("StrategyId")
                        .HasColumnType("uuid")
                        .HasColumnName("strategy_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("alert_type");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("idx_alerts_account");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_alerts_created");

                    b.HasIndex("Severity")
                        .HasDatabaseName("idx_alerts_severity");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_alerts_status");

                    b.ToTable("alerts", "monitoring");
                });

            modelBuilder.Entity("AlgoTrading.Core.Entities.Monitoring.SystemMetric", b =>
                {
                    b.Property<DateTime>("MetricTimestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("metric_timestamp");

                    b.Property<decimal?>("ApiAvgLatencyMs")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("api_avg_latency_ms");

                    b.Property<int?>("ApiErrorCount")
                        .HasColumnType("integer")
                        .HasColumnName("api_error_count");

                    b.Property<int?>("ApiRequestCount")
                        .HasColumnType("integer")
                        .HasColumnName("api_request_count");

                    b.Property<decimal?>("CpuUsagePercent")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("cpu_usage_percent");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DbConnections")
                        .HasColumnType("integer")
                        .HasColumnName("db_connections");

                    b.Property<decimal?>("DbQueryTimeMs")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("db_query_time_ms");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("MemoryTotalMb")
                        .HasColumnType("bigint")
                        .HasColumnName("memory_total_mb");

                    b.Property<decimal?>("MemoryUsagePercent")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("memory_usage_percent");

                    b.Property<long?>("MemoryUsedMb")
                        .HasColumnType("bigint")
                        .HasColumnName("memory_used_mb");

                    b.Property<decimal?>("NetworkInMbps")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("network_in_mbps");

                    b.Property<decimal?>("NetworkOutMbps")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("network_out_mbps");

                    b.HasKey("MetricTimestamp");

                    b.ToTable("system_metrics", "monitoring");
                });

            modelBuilder.Entity("AlgoTrading.Core.Entities.Monitoring.TradingMetric", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("MetricTimestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("metric_timestamp");

                    b.Property<decimal?>("AvgExecutionTimeMs")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("avg_execution_time_ms");

                    b.Property<int>("ClosedPositions")
                        .HasColumnType("integer")
                        .HasColumnName("closed_positions");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OpenPositions")
                        .HasColumnType("integer")
                        .HasColumnName("open_positions");

                    b.Property<int>("OrdersCancelled")
                        .HasColumnType("integer")
                        .HasColumnName("orders_cancelled");

                    b.Property<int>("OrdersFilled")
                        .HasColumnType("integer")
                        .HasColumnName("orders_filled");

                    b.Property<int>("OrdersRejected")
                        .HasColumnType("integer")
                        .HasColumnName("orders_rejected");

                    b.Property<int>("OrdersSubmitted")
                        .HasColumnType("integer")
                        .HasColumnName("orders_submitted");

                    b.HasKey("AccountId", "MetricTimestamp");

                    b.HasIndex("AccountId", "MetricTimestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_trading_metrics_account");

                    b.ToTable("trading_metrics", "monitoring");
                });

            modelBuilder.Entity("AlgoTrading.Core.Entities.Portfolio.AccountBalanceHistory", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("BalanceDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("balance_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at");

                    b.HasKey("AccountId", "BalanceDate");

                    b.HasIndex("AccountId", "BalanceDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_account_balance_account");

                    b.ToTable("account_balance_history", "account");
                });

            modelBuilder.Entity("AlgoTrading.Core.Entities.Portfolio.AccountRestriction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("applied_at");

                    b.Property<Guid>("AppliedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("applied_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("restriction_status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("restriction_type");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("idx_account_restrictions_account");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_account_restrictions_status");

                    b.ToTable("account_restrictions", "account");
                });

            modelBuilder.Entity("AlgoTrading.Core.Entities.Portfolio.AccountWithdrawal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountHolderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("account_holder_name");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("approved_at");

                    b.Property<string>("BankAccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bank_account_number");

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("bank_code");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("withdrawal_status");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("idx_withdrawals_account");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_withdrawals_status");

                    b.ToTable("account_withdrawals", "account", t =>
                        {
                            t.HasCheckConstraint("chk_withdrawal_amount", "amount > 0");
                        });
                });

            modelBuilder.Entity("AlgoTrading.Core.Entities.Portfolio.PerformanceRecord", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("record_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CumulativeReturnPercent")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("cumulative_return_percent");

                    b.Property<decimal>("DailyReturnPercent")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("daily_return_percent");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("MaxDrawdown")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("max_drawdown");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at");

                    b.Property<decimal?>("SharpeRatio")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("sharpe_ratio");

                    b.Property<decimal?>("WinRate")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("win_rate");

                    b.HasKey("AccountId", "RecordDate");

                    b.HasIndex("AccountId", "RecordDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_performance_account");

                    b.ToTable("performance_records", "account");
                });

            modelBuilder.Entity("AlgoTrading.Core.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_attempts");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastLoginIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("last_login_ip");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamptz")
                        .HasColumnName("locked_until");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("user_role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("user_status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_users_email");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_users_status");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("idx_users_username");

                    b.ToTable("users", "public", t =>
                        {
                            t.HasCheckConstraint("chk_failed_login_attempts", "failed_login_attempts >= 0");
                        });
                });

            modelBuilder.Entity("AlgoTrading.Core.Entities.MarketData.MarketData", b =>
                {
                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "ChangeAmount", b1 =>
                        {
                            b1.Property<string>("MarketDataStockCode")
                                .HasColumnType("character varying(20)");

                            b1.Property<DateTime>("MarketDataDataTimestamp")
                                .HasColumnType("timestamptz");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("change_amount");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("MarketDataStockCode", "MarketDataDataTimestamp");

                            b1.ToTable("market_data", "market");

                            b1.WithOwner()
                                .HasForeignKey("MarketDataStockCode", "MarketDataDataTimestamp");
                        });

                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "ClosePrice", b1 =>
                        {
                            b1.Property<string>("MarketDataStockCode")
                                .HasColumnType("character varying(20)");

                            b1.Property<DateTime>("MarketDataDataTimestamp")
                                .HasColumnType("timestamptz");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("close_price");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("MarketDataStockCode", "MarketDataDataTimestamp");

                            b1.ToTable("market_data", "market");

                            b1.WithOwner()
                                .HasForeignKey("MarketDataStockCode", "MarketDataDataTimestamp");
                        });

                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "HighPrice", b1 =>
                        {
                            b1.Property<string>("MarketDataStockCode")
                                .HasColumnType("character varying(20)");

                            b1.Property<DateTime>("MarketDataDataTimestamp")
                                .HasColumnType("timestamptz");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("high_price");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("MarketDataStockCode", "MarketDataDataTimestamp");

                            b1.ToTable("market_data", "market");

                            b1.WithOwner()
                                .HasForeignKey("MarketDataStockCode", "MarketDataDataTimestamp");
                        });

                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "LowPrice", b1 =>
                        {
                            b1.Property<string>("MarketDataStockCode")
                                .HasColumnType("character varying(20)");

                            b1.Property<DateTime>("MarketDataDataTimestamp")
                                .HasColumnType("timestamptz");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("low_price");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("MarketDataStockCode", "MarketDataDataTimestamp");

                            b1.ToTable("market_data", "market");

                            b1.WithOwner()
                                .HasForeignKey("MarketDataStockCode", "MarketDataDataTimestamp");
                        });

                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "OpenPrice", b1 =>
                        {
                            b1.Property<string>("MarketDataStockCode")
                                .HasColumnType("character varying(20)");

                            b1.Property<DateTime>("MarketDataDataTimestamp")
                                .HasColumnType("timestamptz");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("open_price");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("MarketDataStockCode", "MarketDataDataTimestamp");

                            b1.ToTable("market_data", "market");

                            b1.WithOwner()
                                .HasForeignKey("MarketDataStockCode", "MarketDataDataTimestamp");
                        });

                    b.Navigation("ChangeAmount");

                    b.Navigation("ClosePrice")
                        .IsRequired();

                    b.Navigation("HighPrice")
                        .IsRequired();

                    b.Navigation("LowPrice")
                        .IsRequired();

                    b.Navigation("OpenPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("AlgoTrading.Core.Entities.MarketData.OrderBook", b =>
                {
                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "AskPrice1", b1 =>
                        {
                            b1.Property<Guid>("OrderBookId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("ask_price_1");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("OrderBookId");

                            b1.ToTable("order_book", "market");

                            b1.WithOwner()
                                .HasForeignKey("OrderBookId");
                        });

                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "AskPrice10", b1 =>
                        {
                            b1.Property<Guid>("OrderBookId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("ask_price_10");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("OrderBookId");

                            b1.ToTable("order_book", "market");

                            b1.WithOwner()
                                .HasForeignKey("OrderBookId");
                        });

                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "AskPrice2", b1 =>
                        {
                            b1.Property<Guid>("OrderBookId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("ask_price_2");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("OrderBookId");

                            b1.ToTable("order_book", "market");

                            b1.WithOwner()
                                .HasForeignKey("OrderBookId");
                        });

                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "AskPrice3", b1 =>
                        {
                            b1.Property<Guid>("OrderBookId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("ask_price_3");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("OrderBookId");

                            b1.ToTable("order_book", "market");

                            b1.WithOwner()
                                .HasForeignKey("OrderBookId");
                        });

                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "AskPrice4", b1 =>
                        {
                            b1.Property<Guid>("OrderBookId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("ask_price_4");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("OrderBookId");

                            b1.ToTable("order_book", "market");

                            b1.WithOwner()
                                .HasForeignKey("OrderBookId");
                        });

                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "AskPrice5", b1 =>
                        {
                            b1.Property<Guid>("OrderBookId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("ask_price_5");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("OrderBookId");

                            b1.ToTable("order_book", "market");

                            b1.WithOwner()
                                .HasForeignKey("OrderBookId");
                        });

                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "AskPrice6", b1 =>
                        {
                            b1.Property<Guid>("OrderBookId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("ask_price_6");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("OrderBookId");

                            b1.ToTable("order_book", "market");

                            b1.WithOwner()
                                .HasForeignKey("OrderBookId");
                        });

                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "AskPrice7", b1 =>
                        {
                            b1.Property<Guid>("OrderBookId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("ask_price_7");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("OrderBookId");

                            b1.ToTable("order_book", "market");

                            b1.WithOwner()
                                .HasForeignKey("OrderBookId");
                        });

                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "AskPrice8", b1 =>
                        {
                            b1.Property<Guid>("OrderBookId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("ask_price_8");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("OrderBookId");

                            b1.ToTable("order_book", "market");

                            b1.WithOwner()
                                .HasForeignKey("OrderBookId");
                        });

                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "AskPrice9", b1 =>
                        {
                            b1.Property<Guid>("OrderBookId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("ask_price_9");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("OrderBookId");

                            b1.ToTable("order_book", "market");

                            b1.WithOwner()
                                .HasForeignKey("OrderBookId");
                        });

                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "BidPrice1", b1 =>
                        {
                            b1.Property<Guid>("OrderBookId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("bid_price_1");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("OrderBookId");

                            b1.ToTable("order_book", "market");

                            b1.WithOwner()
                                .HasForeignKey("OrderBookId");
                        });

                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "BidPrice10", b1 =>
                        {
                            b1.Property<Guid>("OrderBookId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("bid_price_10");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("OrderBookId");

                            b1.ToTable("order_book", "market");

                            b1.WithOwner()
                                .HasForeignKey("OrderBookId");
                        });

                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "BidPrice2", b1 =>
                        {
                            b1.Property<Guid>("OrderBookId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("bid_price_2");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("OrderBookId");

                            b1.ToTable("order_book", "market");

                            b1.WithOwner()
                                .HasForeignKey("OrderBookId");
                        });

                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "BidPrice3", b1 =>
                        {
                            b1.Property<Guid>("OrderBookId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("bid_price_3");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("OrderBookId");

                            b1.ToTable("order_book", "market");

                            b1.WithOwner()
                                .HasForeignKey("OrderBookId");
                        });

                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "BidPrice4", b1 =>
                        {
                            b1.Property<Guid>("OrderBookId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("bid_price_4");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("OrderBookId");

                            b1.ToTable("order_book", "market");

                            b1.WithOwner()
                                .HasForeignKey("OrderBookId");
                        });

                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "BidPrice5", b1 =>
                        {
                            b1.Property<Guid>("OrderBookId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("bid_price_5");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("OrderBookId");

                            b1.ToTable("order_book", "market");

                            b1.WithOwner()
                                .HasForeignKey("OrderBookId");
                        });

                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "BidPrice6", b1 =>
                        {
                            b1.Property<Guid>("OrderBookId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("bid_price_6");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("OrderBookId");

                            b1.ToTable("order_book", "market");

                            b1.WithOwner()
                                .HasForeignKey("OrderBookId");
                        });

                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "BidPrice7", b1 =>
                        {
                            b1.Property<Guid>("OrderBookId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("bid_price_7");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("OrderBookId");

                            b1.ToTable("order_book", "market");

                            b1.WithOwner()
                                .HasForeignKey("OrderBookId");
                        });

                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "BidPrice8", b1 =>
                        {
                            b1.Property<Guid>("OrderBookId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("bid_price_8");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("OrderBookId");

                            b1.ToTable("order_book", "market");

                            b1.WithOwner()
                                .HasForeignKey("OrderBookId");
                        });

                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "BidPrice9", b1 =>
                        {
                            b1.Property<Guid>("OrderBookId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("bid_price_9");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("OrderBookId");

                            b1.ToTable("order_book", "market");

                            b1.WithOwner()
                                .HasForeignKey("OrderBookId");
                        });

                    b.Navigation("AskPrice1");

                    b.Navigation("AskPrice10");

                    b.Navigation("AskPrice2");

                    b.Navigation("AskPrice3");

                    b.Navigation("AskPrice4");

                    b.Navigation("AskPrice5");

                    b.Navigation("AskPrice6");

                    b.Navigation("AskPrice7");

                    b.Navigation("AskPrice8");

                    b.Navigation("AskPrice9");

                    b.Navigation("BidPrice1");

                    b.Navigation("BidPrice10");

                    b.Navigation("BidPrice2");

                    b.Navigation("BidPrice3");

                    b.Navigation("BidPrice4");

                    b.Navigation("BidPrice5");

                    b.Navigation("BidPrice6");

                    b.Navigation("BidPrice7");

                    b.Navigation("BidPrice8");

                    b.Navigation("BidPrice9");
                });

            modelBuilder.Entity("AlgoTrading.Core.Entities.MarketData.StockInfo", b =>
                {
                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "LowerLimitPrice", b1 =>
                        {
                            b1.Property<string>("StockInfoId")
                                .HasColumnType("character varying(20)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("lower_limit_price");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("StockInfoId");

                            b1.ToTable("stock_info", "market");

                            b1.WithOwner()
                                .HasForeignKey("StockInfoId");
                        });

                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "UpperLimitPrice", b1 =>
                        {
                            b1.Property<string>("StockInfoId")
                                .HasColumnType("character varying(20)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("upper_limit_price");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("StockInfoId");

                            b1.ToTable("stock_info", "market");

                            b1.WithOwner()
                                .HasForeignKey("StockInfoId");
                        });

                    b.Navigation("LowerLimitPrice");

                    b.Navigation("UpperLimitPrice");
                });

            modelBuilder.Entity("AlgoTrading.Core.Entities.MarketData.TickData", b =>
                {
                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "ExecutionPrice", b1 =>
                        {
                            b1.Property<string>("TickDataStockCode")
                                .HasColumnType("character varying(20)");

                            b1.Property<DateTime>("TickDataTickTimestamp")
                                .HasColumnType("timestamptz");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("execution_price");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("TickDataStockCode", "TickDataTickTimestamp");

                            b1.ToTable("tick_data", "market");

                            b1.WithOwner()
                                .HasForeignKey("TickDataStockCode", "TickDataTickTimestamp");
                        });

                    b.Navigation("ExecutionPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("AlgoTrading.Core.Entities.Monitoring.TradingMetric", b =>
                {
                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "RealizedPl", b1 =>
                        {
                            b1.Property<Guid>("TradingMetricAccountId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("TradingMetricMetricTimestamp")
                                .HasColumnType("timestamptz");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("realized_pl");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("TradingMetricAccountId", "TradingMetricMetricTimestamp");

                            b1.ToTable("trading_metrics", "monitoring");

                            b1.WithOwner()
                                .HasForeignKey("TradingMetricAccountId", "TradingMetricMetricTimestamp");
                        });

                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "TotalExecutionAmount", b1 =>
                        {
                            b1.Property<Guid>("TradingMetricAccountId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("TradingMetricMetricTimestamp")
                                .HasColumnType("timestamptz");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("total_execution_amount");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("TradingMetricAccountId", "TradingMetricMetricTimestamp");

                            b1.ToTable("trading_metrics", "monitoring");

                            b1.WithOwner()
                                .HasForeignKey("TradingMetricAccountId", "TradingMetricMetricTimestamp");
                        });

                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "UnrealizedPl", b1 =>
                        {
                            b1.Property<Guid>("TradingMetricAccountId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("TradingMetricMetricTimestamp")
                                .HasColumnType("timestamptz");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("unrealized_pl");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("TradingMetricAccountId", "TradingMetricMetricTimestamp");

                            b1.ToTable("trading_metrics", "monitoring");

                            b1.WithOwner()
                                .HasForeignKey("TradingMetricAccountId", "TradingMetricMetricTimestamp");
                        });

                    b.Navigation("RealizedPl");

                    b.Navigation("TotalExecutionAmount");

                    b.Navigation("UnrealizedPl");
                });

            modelBuilder.Entity("AlgoTrading.Core.Entities.Portfolio.AccountBalanceHistory", b =>
                {
                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "CashBalance", b1 =>
                        {
                            b1.Property<Guid>("AccountBalanceHistoryAccountId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("AccountBalanceHistoryBalanceDate")
                                .HasColumnType("timestamptz");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("cash_balance");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("AccountBalanceHistoryAccountId", "AccountBalanceHistoryBalanceDate");

                            b1.ToTable("account_balance_history", "account");

                            b1.WithOwner()
                                .HasForeignKey("AccountBalanceHistoryAccountId", "AccountBalanceHistoryBalanceDate");
                        });

                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "TotalAssets", b1 =>
                        {
                            b1.Property<Guid>("AccountBalanceHistoryAccountId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("AccountBalanceHistoryBalanceDate")
                                .HasColumnType("timestamptz");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("total_assets");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("AccountBalanceHistoryAccountId", "AccountBalanceHistoryBalanceDate");

                            b1.ToTable("account_balance_history", "account");

                            b1.WithOwner()
                                .HasForeignKey("AccountBalanceHistoryAccountId", "AccountBalanceHistoryBalanceDate");
                        });

                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "TotalEvaluation", b1 =>
                        {
                            b1.Property<Guid>("AccountBalanceHistoryAccountId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("AccountBalanceHistoryBalanceDate")
                                .HasColumnType("timestamptz");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("total_evaluation");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("AccountBalanceHistoryAccountId", "AccountBalanceHistoryBalanceDate");

                            b1.ToTable("account_balance_history", "account");

                            b1.WithOwner()
                                .HasForeignKey("AccountBalanceHistoryAccountId", "AccountBalanceHistoryBalanceDate");
                        });

                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "TotalProfitLoss", b1 =>
                        {
                            b1.Property<Guid>("AccountBalanceHistoryAccountId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("AccountBalanceHistoryBalanceDate")
                                .HasColumnType("timestamptz");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("total_pl");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("AccountBalanceHistoryAccountId", "AccountBalanceHistoryBalanceDate");

                            b1.ToTable("account_balance_history", "account");

                            b1.WithOwner()
                                .HasForeignKey("AccountBalanceHistoryAccountId", "AccountBalanceHistoryBalanceDate");
                        });

                    b.Navigation("CashBalance")
                        .IsRequired();

                    b.Navigation("TotalAssets")
                        .IsRequired();

                    b.Navigation("TotalEvaluation")
                        .IsRequired();

                    b.Navigation("TotalProfitLoss")
                        .IsRequired();
                });

            modelBuilder.Entity("AlgoTrading.Core.Entities.Portfolio.AccountWithdrawal", b =>
                {
                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("AccountWithdrawalId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.HasKey("AccountWithdrawalId");

                            b1.ToTable("account_withdrawals", "account");

                            b1.WithOwner()
                                .HasForeignKey("AccountWithdrawalId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("AlgoTrading.Core.Entities.Portfolio.PerformanceRecord", b =>
                {
                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "CumulativeReturn", b1 =>
                        {
                            b1.Property<Guid>("PerformanceRecordAccountId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("PerformanceRecordRecordDate")
                                .HasColumnType("timestamptz");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("cumulative_return");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("PerformanceRecordAccountId", "PerformanceRecordRecordDate");

                            b1.ToTable("performance_records", "account");

                            b1.WithOwner()
                                .HasForeignKey("PerformanceRecordAccountId", "PerformanceRecordRecordDate");
                        });

                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "DailyReturn", b1 =>
                        {
                            b1.Property<Guid>("PerformanceRecordAccountId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("PerformanceRecordRecordDate")
                                .HasColumnType("timestamptz");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("daily_return");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("PerformanceRecordAccountId", "PerformanceRecordRecordDate");

                            b1.ToTable("performance_records", "account");

                            b1.WithOwner()
                                .HasForeignKey("PerformanceRecordAccountId", "PerformanceRecordRecordDate");
                        });

                    b.OwnsOne("AlgoTrading.Core.ValueObjects.Money", "EquityValue", b1 =>
                        {
                            b1.Property<Guid>("PerformanceRecordAccountId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("PerformanceRecordRecordDate")
                                .HasColumnType("timestamptz");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("equity_value");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("PerformanceRecordAccountId", "PerformanceRecordRecordDate");

                            b1.ToTable("performance_records", "account");

                            b1.WithOwner()
                                .HasForeignKey("PerformanceRecordAccountId", "PerformanceRecordRecordDate");
                        });

                    b.Navigation("CumulativeReturn");

                    b.Navigation("DailyReturn")
                        .IsRequired();

                    b.Navigation("EquityValue")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
