using AlgoTrading.Core.ValueObjects;

namespace AlgoTrading.Core.Entities.Strategy;

/// <summary>
/// description(설명) : Strategy Signal Entity - Represents a trading signal generated by a strategy (전략 시그널 엔티티 - 전략이 생성한 매매 시그널을 나타냄)
/// Details(상세설명) : Contains signal type, strength, confidence, and suggested entry/exit prices for automated trading decisions (자동 매매 결정을 위한 시그널 유형, 강도, 신뢰도 및 제안 진입/청산 가격 포함)
/// Applied technology patterns(적용기술패턴) : Entity Pattern (엔티티 패턴), Domain-Driven Design (도메인 주도 설계), State Machine Pattern (상태 머신 패턴)
/// </summary>
public sealed class StrategySignal : Entity<StrategySignalId>
{
    /// <summary>
    /// 시그널을 생성한 전략 ID
    /// </summary>
    public StrategyId StrategyId { get; private set; }

    /// <summary>
    /// 종목 코드
    /// </summary>
    public StockCode StockCode { get; private set; }

    /// <summary>
    /// 시그널 유형 (매수/매도/보유 등)
    /// </summary>
    public SignalType SignalType { get; private set; }

    /// <summary>
    /// 시그널 강도 (0-100)
    /// </summary>
    public decimal Strength { get; private set; }

    /// <summary>
    /// 시그널 신뢰도 (0-1)
    /// </summary>
    public decimal Confidence { get; private set; }

    /// <summary>
    /// 권장 진입 가격
    /// </summary>
    public decimal? SuggestedPrice { get; private set; }

    /// <summary>
    /// 권장 수량
    /// </summary>
    public int? SuggestedQuantity { get; private set; }

    /// <summary>
    /// 권장 손절가
    /// </summary>
    public decimal? StopLossPrice { get; private set; }

    /// <summary>
    /// 권장 익절가
    /// </summary>
    public decimal? TakeProfitPrice { get; private set; }

    /// <summary>
    /// 시그널 생성 시간
    /// </summary>
    public DateTime GeneratedAt { get; private set; }

    /// <summary>
    /// 시그널 만료 시간
    /// </summary>
    public DateTime? ExpiresAt { get; private set; }

    /// <summary>
    /// 시그널 상태
    /// </summary>
    public SignalStatus Status { get; private set; }

    /// <summary>
    /// 시그널 실행 여부
    /// </summary>
    public bool WasActedUpon { get; private set; }

    /// <summary>
    /// 연관된 주문 ID (실행된 경우)
    /// </summary>
    public Guid? OrderId { get; private set; }

    /// <summary>
    /// 시그널 메타데이터/컨텍스트
    /// </summary>
    public Dictionary<string, object> Metadata { get; private set; }

    /// <summary>
    /// 시그널 발생 이유/설명
    /// </summary>
    public string? Reason { get; private set; }

    private StrategySignal()
    {
        Metadata = new Dictionary<string, object>();
    }

    private StrategySignal(
        StrategySignalId id,
        StrategyId strategyId,
        StockCode stockCode,
        SignalType signalType,
        decimal strength,
        decimal confidence,
        DateTime generatedAt)
    {
        Id = id;
        StrategyId = strategyId;
        StockCode = stockCode;
        SignalType = signalType;
        Strength = Math.Clamp(strength, 0, 100);
        Confidence = Math.Clamp(confidence, 0, 1);
        GeneratedAt = generatedAt;
        Status = SignalStatus.Active;
        WasActedUpon = false;
        Metadata = new Dictionary<string, object>();
    }

    /// <summary>
    /// description(설명) : Create a new strategy signal (새 전략 시그널 생성)
    /// Details(상세설명) : Factory method to create a signal when strategy identifies a trading opportunity (전략이 매매 기회를 식별할 때 시그널을 생성하는 팩토리 메서드)
    /// Applied technology patterns(적용기술패턴) : Factory Pattern (팩토리 패턴), Domain-Driven Design (도메인 주도 설계)
    /// </summary>
    /// <returns>Newly created StrategySignal instance (새로 생성된 전략 시그널 인스턴스)</returns>
    public static StrategySignal Create(
        StrategyId strategyId,
        StockCode stockCode,
        SignalType signalType,
        decimal strength,
        decimal confidence)
    {
        var id = new StrategySignalId(Guid.NewGuid());
        return new StrategySignal(id, strategyId, stockCode, signalType, strength, confidence, DateTime.UtcNow);
    }

    /// <summary>
    /// description(설명) : Set suggested entry, stop-loss, and take-profit prices (권장 진입가, 손절가, 익절가 설정)
    /// Details(상세설명) : Allows setting recommended price levels for risk management (리스크 관리를 위한 권장 가격 수준 설정)
    /// Applied technology patterns(적용기술패턴) : Domain-Driven Design (도메인 주도 설계)
    /// </summary>
    public void SetSuggestedPrices(decimal? entryPrice, decimal? stopLoss, decimal? takeProfit)
    {
        SuggestedPrice = entryPrice;
        StopLossPrice = stopLoss;
        TakeProfitPrice = takeProfit;
        MarkAsModified();
    }

    /// <summary>
    /// Set suggested quantity
    /// </summary>
    public void SetSuggestedQuantity(int quantity)
    {
        if (quantity < 0)
            throw new ArgumentException("Quantity cannot be negative", nameof(quantity));

        SuggestedQuantity = quantity;
        MarkAsModified();
    }

    /// <summary>
    /// Set expiration time
    /// </summary>
    public void SetExpiration(DateTime expiresAt)
    {
        if (expiresAt <= GeneratedAt)
            throw new ArgumentException("Expiration must be after generation time");

        ExpiresAt = expiresAt;
        MarkAsModified();
    }

    /// <summary>
    /// Set signal reason
    /// </summary>
    public void SetReason(string reason)
    {
        Reason = reason;
        MarkAsModified();
    }

    /// <summary>
    /// description(설명) : Mark signal as executed with order ID (시그널을 주문 ID와 함께 실행됨으로 표시)
    /// Details(상세설명) : Updates signal status to executed and links to the order that was placed (시그널 상태를 실행됨으로 업데이트하고 생성된 주문과 연결)
    /// Applied technology patterns(적용기술패턴) : State Machine Pattern (상태 머신 패턴), Domain-Driven Design (도메인 주도 설계)
    /// </summary>
    public void MarkAsExecuted(Guid orderId)
    {
        Status = SignalStatus.Executed;
        WasActedUpon = true;
        OrderId = orderId;
        MarkAsModified();
    }

    /// <summary>
    /// Mark signal as expired
    /// </summary>
    public void Expire()
    {
        Status = SignalStatus.Expired;
        MarkAsModified();
    }

    /// <summary>
    /// Mark signal as cancelled
    /// </summary>
    public void Cancel()
    {
        Status = SignalStatus.Cancelled;
        MarkAsModified();
    }

    /// <summary>
    /// Check if signal is expired
    /// </summary>
    public bool IsExpired()
    {
        return Status == SignalStatus.Expired ||
               (ExpiresAt.HasValue && DateTime.UtcNow > ExpiresAt.Value);
    }

    /// <summary>
    /// Check if signal is still active
    /// </summary>
    public bool IsActive()
    {
        return Status == SignalStatus.Active && !IsExpired();
    }

    /// <summary>
    /// Add metadata
    /// </summary>
    public void AddMetadata(string key, object value)
    {
        Metadata[key] = value;
        MarkAsModified();
    }

    /// <summary>
    /// description(설명) : Calculate risk-reward ratio (위험-보상 비율 계산)
    /// Details(상세설명) : Computes the ratio of potential reward to risk based on suggested prices (제안된 가격을 기반으로 잠재적 보상 대 위험 비율 계산)
    /// Applied technology patterns(적용기술패턴) : Domain-Driven Design (도메인 주도 설계)
    /// </summary>
    /// <returns>Risk-reward ratio or null if prices not set (위험-보상 비율 또는 가격 미설정시 null)</returns>
    public decimal? GetRiskRewardRatio()
    {
        if (!SuggestedPrice.HasValue || !StopLossPrice.HasValue || !TakeProfitPrice.HasValue)
            return null;

        var risk = Math.Abs(SuggestedPrice.Value - StopLossPrice.Value);
        var reward = Math.Abs(TakeProfitPrice.Value - SuggestedPrice.Value);

        return risk > 0 ? reward / risk : null;
    }
}

/// <summary>
/// description(설명) : Strategy Signal identifier value object (전략 시그널 식별자 값 객체)
/// Details(상세설명) : Strongly-typed identifier for StrategySignal entity using GUID (GUID를 사용한 전략 시그널 엔티티의 강타입 식별자)
/// Applied technology patterns(적용기술패턴) : Value Object Pattern (값 객체 패턴), Domain-Driven Design (도메인 주도 설계)
/// </summary>
public sealed class StrategySignalId : GuidId
{
    public StrategySignalId(Guid value) : base(value) { }

    public static StrategySignalId New() => new(Guid.NewGuid());
}

/// <summary>
/// description(설명) : Signal type enumeration (시그널 유형 열거형)
/// Details(상세설명) : Categorizes trading signals by action type (매매 시그널을 행동 유형별로 분류)
/// Applied technology patterns(적용기술패턴) : Domain-Driven Design (도메인 주도 설계)
/// </summary>
public enum SignalType
{
    Buy = 1,                    // Buy signal (매수 시그널)
    Sell = 2,                   // Sell signal (매도 시그널)
    StrongBuy = 3,              // Strong buy signal (강한 매수 시그널)
    StrongSell = 4,             // Strong sell signal (강한 매도 시그널)
    Hold = 5,                   // Hold position (보유)
    ClosePosition = 6           // Close existing position (포지션 청산)
}

/// <summary>
/// description(설명) : Signal status enumeration (시그널 상태 열거형)
/// Details(상세설명) : Tracks the lifecycle status of a trading signal (매매 시그널의 생명주기 상태 추적)
/// Applied technology patterns(적용기술패턴) : State Machine Pattern (상태 머신 패턴), Domain-Driven Design (도메인 주도 설계)
/// </summary>
public enum SignalStatus
{
    Active = 1,                 // Signal is active and waiting (시그널 활성 대기 중)
    Executed = 2,               // Signal was executed (시그널 실행됨)
    Expired = 3,                // Signal expired (시그널 만료됨)
    Cancelled = 4               // Signal cancelled (시그널 취소됨)
}
